export const propertiesNames = {
  closeTime: 'closing time',
  count: 'count',
  firstId: 'first id',
  highPrice: 'highest price',
  lastId: 'lastest id',
  lastPrice: 'lastest price',
  lowPrice: 'lowest price',
  openPrice: 'open price',
  openTime: 'open time',
  priceChange: 'price change',
  priceChangePercent: 'price change (%)',
  quoteVolume: 'quote volume',
  symbol: 'symbol',
  volume: 'volume',
  weightedAvgPrice: 'weighted average price',
  prevClosePrice: 'previous close price',
  askPrice: 'ask price',
  askQty: 'ask quantity',
  bidPrice: 'bid price',
  bidQty: 'bid quantity',
  lastQty: 'lastest quantity',
  price: 'price',
  qty: 'qty',
  quoteQty: 'quote quantity',
  time: 'time',
  isBuyerMaker: 'buyer maker',
  isBestMatch: 'best match',
};
